name: "release"

on:
    release:
        types: [published]

jobs:
    release:
        name: 🚀 release
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v3.0.2

            - name: 🟢 node
              uses: actions/setup-node@master
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org

            - name: 🔨 Install PNPM
              uses: pnpm/action-setup@v2.0.1
              id: pnpm-install
              with:
                version: 7
                run_install: false

            - name: 🔨 build
              run: |
                pnpm i
                pnpm run build

            - name: 🚀 publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}